// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: health.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct VitalOSProtocol_HealthAggregatedDataEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Start of the bucket (UTC)
  public var timestamp: Int64 = 0

  /// HR Data
  public var avgHeartRate: Int32 = 0

  public var hrCount: Int32 = 0

  public var maxHr: Int32 = 0

  public var minHr: Int32 = 0

  /// Calorie Data
  public var activeCalories: Float = 0

  public var passiveCalories: Float = 0

  /// Step Data
  public var steps: Int32 = 0

  /// HR Zone Durations (in milliseconds)
  public var zone1DurationMs: Int64 = 0

  public var zone2DurationMs: Int64 = 0

  public var zone3DurationMs: Int64 = 0

  public var zone4DurationMs: Int64 = 0

  public var zone5DurationMs: Int64 = 0

  /// Oxygen Saturation
  public var spo2: Float = 0

  /// The total duration this segment was active for
  public var activeDurationMs: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VitalOSProtocol_WeeklyHealthSummary: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var windowStartTimestamp: Int64 = 0

  public var dailySummaries: [VitalOSProtocol_HealthAggregatedDataEntry] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VitalOSProtocol_HealthSyncRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unix timestamp (ms) inclusive
  public var startTimestamp: Int64 = 0

  /// Unix timestamp (ms) exclusive
  public var endTimestamp: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VitalOSProtocol_HealthDataUpload: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var records: [VitalOSProtocol_HealthAggregatedDataEntry] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Watch -> App: bulk sync response (one command ID; oneof distinguishes chunk vs terminal complete).
public struct VitalOSProtocol_HealthSyncComplete: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VitalOSProtocol_HealthSyncNotification: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var payload: VitalOSProtocol_HealthSyncNotification.OneOf_Payload? = nil

  public var data: VitalOSProtocol_HealthDataUpload {
    get {
      if case .data(let v)? = payload {return v}
      return VitalOSProtocol_HealthDataUpload()
    }
    set {payload = .data(newValue)}
  }

  public var complete: VitalOSProtocol_HealthSyncComplete {
    get {
      if case .complete(let v)? = payload {return v}
      return VitalOSProtocol_HealthSyncComplete()
    }
    set {payload = .complete(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Payload: Equatable, Sendable {
    case data(VitalOSProtocol_HealthDataUpload)
    case complete(VitalOSProtocol_HealthSyncComplete)

  }

  public init() {}
}

public struct VitalOSProtocol_HealthDataNotification: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Start of available data range (millis since epoch)
  public var startTimestamp: Int64 = 0

  /// End of available data range (millis since epoch)
  public var endTimestamp: Int64 = 0

  /// Number of records available
  public var recordCount: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "VitalOSProtocol"

extension VitalOSProtocol_HealthAggregatedDataEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HealthAggregatedDataEntry"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}timestamp\0\u{3}avg_heart_rate\0\u{3}hr_count\0\u{3}max_hr\0\u{3}min_hr\0\u{3}active_calories\0\u{3}passive_calories\0\u{1}steps\0\u{3}zone_1_duration_ms\0\u{3}zone_2_duration_ms\0\u{3}zone_3_duration_ms\0\u{3}zone_4_duration_ms\0\u{3}zone_5_duration_ms\0\u{1}spo2\0\u{3}active_duration_ms\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.timestamp) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.avgHeartRate) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.hrCount) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.maxHr) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.minHr) }()
      case 6: try { try decoder.decodeSingularFloatField(value: &self.activeCalories) }()
      case 7: try { try decoder.decodeSingularFloatField(value: &self.passiveCalories) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.steps) }()
      case 9: try { try decoder.decodeSingularInt64Field(value: &self.zone1DurationMs) }()
      case 10: try { try decoder.decodeSingularInt64Field(value: &self.zone2DurationMs) }()
      case 11: try { try decoder.decodeSingularInt64Field(value: &self.zone3DurationMs) }()
      case 12: try { try decoder.decodeSingularInt64Field(value: &self.zone4DurationMs) }()
      case 13: try { try decoder.decodeSingularInt64Field(value: &self.zone5DurationMs) }()
      case 14: try { try decoder.decodeSingularFloatField(value: &self.spo2) }()
      case 15: try { try decoder.decodeSingularInt64Field(value: &self.activeDurationMs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.timestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.timestamp, fieldNumber: 1)
    }
    if self.avgHeartRate != 0 {
      try visitor.visitSingularInt32Field(value: self.avgHeartRate, fieldNumber: 2)
    }
    if self.hrCount != 0 {
      try visitor.visitSingularInt32Field(value: self.hrCount, fieldNumber: 3)
    }
    if self.maxHr != 0 {
      try visitor.visitSingularInt32Field(value: self.maxHr, fieldNumber: 4)
    }
    if self.minHr != 0 {
      try visitor.visitSingularInt32Field(value: self.minHr, fieldNumber: 5)
    }
    if self.activeCalories.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.activeCalories, fieldNumber: 6)
    }
    if self.passiveCalories.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.passiveCalories, fieldNumber: 7)
    }
    if self.steps != 0 {
      try visitor.visitSingularInt32Field(value: self.steps, fieldNumber: 8)
    }
    if self.zone1DurationMs != 0 {
      try visitor.visitSingularInt64Field(value: self.zone1DurationMs, fieldNumber: 9)
    }
    if self.zone2DurationMs != 0 {
      try visitor.visitSingularInt64Field(value: self.zone2DurationMs, fieldNumber: 10)
    }
    if self.zone3DurationMs != 0 {
      try visitor.visitSingularInt64Field(value: self.zone3DurationMs, fieldNumber: 11)
    }
    if self.zone4DurationMs != 0 {
      try visitor.visitSingularInt64Field(value: self.zone4DurationMs, fieldNumber: 12)
    }
    if self.zone5DurationMs != 0 {
      try visitor.visitSingularInt64Field(value: self.zone5DurationMs, fieldNumber: 13)
    }
    if self.spo2.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.spo2, fieldNumber: 14)
    }
    if self.activeDurationMs != 0 {
      try visitor.visitSingularInt64Field(value: self.activeDurationMs, fieldNumber: 15)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_HealthAggregatedDataEntry, rhs: VitalOSProtocol_HealthAggregatedDataEntry) -> Bool {
    if lhs.timestamp != rhs.timestamp {return false}
    if lhs.avgHeartRate != rhs.avgHeartRate {return false}
    if lhs.hrCount != rhs.hrCount {return false}
    if lhs.maxHr != rhs.maxHr {return false}
    if lhs.minHr != rhs.minHr {return false}
    if lhs.activeCalories != rhs.activeCalories {return false}
    if lhs.passiveCalories != rhs.passiveCalories {return false}
    if lhs.steps != rhs.steps {return false}
    if lhs.zone1DurationMs != rhs.zone1DurationMs {return false}
    if lhs.zone2DurationMs != rhs.zone2DurationMs {return false}
    if lhs.zone3DurationMs != rhs.zone3DurationMs {return false}
    if lhs.zone4DurationMs != rhs.zone4DurationMs {return false}
    if lhs.zone5DurationMs != rhs.zone5DurationMs {return false}
    if lhs.spo2 != rhs.spo2 {return false}
    if lhs.activeDurationMs != rhs.activeDurationMs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_WeeklyHealthSummary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WeeklyHealthSummary"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}window_start_timestamp\0\u{3}daily_summaries\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.windowStartTimestamp) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.dailySummaries) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.windowStartTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.windowStartTimestamp, fieldNumber: 1)
    }
    if !self.dailySummaries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.dailySummaries, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_WeeklyHealthSummary, rhs: VitalOSProtocol_WeeklyHealthSummary) -> Bool {
    if lhs.windowStartTimestamp != rhs.windowStartTimestamp {return false}
    if lhs.dailySummaries != rhs.dailySummaries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_HealthSyncRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HealthSyncRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}start_timestamp\0\u{3}end_timestamp\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.startTimestamp) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.endTimestamp) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.startTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.startTimestamp, fieldNumber: 1)
    }
    if self.endTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.endTimestamp, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_HealthSyncRequest, rhs: VitalOSProtocol_HealthSyncRequest) -> Bool {
    if lhs.startTimestamp != rhs.startTimestamp {return false}
    if lhs.endTimestamp != rhs.endTimestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_HealthDataUpload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HealthDataUpload"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}records\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.records) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.records.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.records, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_HealthDataUpload, rhs: VitalOSProtocol_HealthDataUpload) -> Bool {
    if lhs.records != rhs.records {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_HealthSyncComplete: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HealthSyncComplete"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_HealthSyncComplete, rhs: VitalOSProtocol_HealthSyncComplete) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_HealthSyncNotification: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HealthSyncNotification"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}data\0\u{1}complete\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: VitalOSProtocol_HealthDataUpload?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .data(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .data(v)
        }
      }()
      case 2: try {
        var v: VitalOSProtocol_HealthSyncComplete?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .complete(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .complete(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.payload {
    case .data?: try {
      guard case .data(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .complete?: try {
      guard case .complete(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_HealthSyncNotification, rhs: VitalOSProtocol_HealthSyncNotification) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_HealthDataNotification: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HealthDataNotification"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}start_timestamp\0\u{3}end_timestamp\0\u{3}record_count\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.startTimestamp) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.endTimestamp) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.recordCount) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.startTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.startTimestamp, fieldNumber: 1)
    }
    if self.endTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.endTimestamp, fieldNumber: 2)
    }
    if self.recordCount != 0 {
      try visitor.visitSingularInt32Field(value: self.recordCount, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_HealthDataNotification, rhs: VitalOSProtocol_HealthDataNotification) -> Bool {
    if lhs.startTimestamp != rhs.startTimestamp {return false}
    if lhs.endTimestamp != rhs.endTimestamp {return false}
    if lhs.recordCount != rhs.recordCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
