// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: local_messages.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// --- Get Phone Battery ---
public struct VitalOSProtocol_GetPhoneBatteryRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VitalOSProtocol_GetPhoneBatteryResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The battery level, from 0 to 100.
  public var level: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// --- Get Weather ---
public struct VitalOSProtocol_GetWeatherRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// The main message that encapsulates all weather data.
public struct VitalOSProtocol_GetWeatherResponse: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var latitude: Double {
    get {_storage._latitude}
    set {_uniqueStorage()._latitude = newValue}
  }

  public var longitude: Double {
    get {_storage._longitude}
    set {_uniqueStorage()._longitude = newValue}
  }

  public var elevation: Double {
    get {_storage._elevation}
    set {_uniqueStorage()._elevation = newValue}
  }

  public var generationTimeMs: Int64 {
    get {_storage._generationTimeMs}
    set {_uniqueStorage()._generationTimeMs = newValue}
  }

  public var utcOffsetMs: Int64 {
    get {_storage._utcOffsetMs}
    set {_uniqueStorage()._utcOffsetMs = newValue}
  }

  public var timestampMs: Int64 {
    get {_storage._timestampMs}
    set {_uniqueStorage()._timestampMs = newValue}
  }

  public var timezone: String {
    get {_storage._timezone}
    set {_uniqueStorage()._timezone = newValue}
  }

  public var timezoneAbbreviation: String {
    get {_storage._timezoneAbbreviation}
    set {_uniqueStorage()._timezoneAbbreviation = newValue}
  }

  public var currentWeatherData: VitalOSProtocol_CurrentWeatherData {
    get {_storage._currentWeatherData ?? VitalOSProtocol_CurrentWeatherData()}
    set {_uniqueStorage()._currentWeatherData = newValue}
  }
  /// Returns true if `currentWeatherData` has been explicitly set.
  public var hasCurrentWeatherData: Bool {_storage._currentWeatherData != nil}
  /// Clears the value of `currentWeatherData`. Subsequent reads from it will return its default value.
  public mutating func clearCurrentWeatherData() {_uniqueStorage()._currentWeatherData = nil}

  public var dailyDataPoints: [VitalOSProtocol_DailyWeatherData] {
    get {_storage._dailyDataPoints}
    set {_uniqueStorage()._dailyDataPoints = newValue}
  }

  public var hourlyDataPoints: [VitalOSProtocol_HourlyWeatherData] {
    get {_storage._hourlyDataPoints}
    set {_uniqueStorage()._hourlyDataPoints = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Represents the current weather conditions.
public struct VitalOSProtocol_CurrentWeatherData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var timestampMs: Int64 = 0

  public var temperature2M: Double = 0

  public var relativeHumidity2M: Double = 0

  public var weatherCode: Int32 = 0

  public var windSpeed10M: Double = 0

  public var windDirection10M: Double = 0

  /// Air Quality Index (AQI)
  public var aqi: Int32 = 0

  /// Particulate matter smaller than 2.5 µm
  public var pm25: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Represents a single point of hourly forecast data.
public struct VitalOSProtocol_HourlyWeatherData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var timestampMs: Int64 = 0

  public var temperature2M: Double = 0

  public var relativeHumidity2M: Double = 0

  public var weatherCode: Int32 = 0

  public var visibility: Double = 0

  public var windSpeed10M: Double = 0

  public var uvIndex: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Represents a single point of daily forecast data.
public struct VitalOSProtocol_DailyWeatherData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var timestampMs: Int64 = 0

  public var weatherCode: Int32 = 0

  public var temperature2MMax: Double = 0

  public var temperature2MMin: Double = 0

  public var sunriseMs: Int64 = 0

  public var sunsetMs: Int64 = 0

  public var precipitationSum: Double = 0

  public var uvIndexMax: Double = 0

  public var windSpeed10MMax: Double = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

//// A wrapper for any local message request sent FROM the watch TO the phone.
public struct VitalOSProtocol_LocalRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var payload: VitalOSProtocol_LocalRequest.OneOf_Payload? = nil

  public var getPhoneBattery: VitalOSProtocol_GetPhoneBatteryRequest {
    get {
      if case .getPhoneBattery(let v)? = payload {return v}
      return VitalOSProtocol_GetPhoneBatteryRequest()
    }
    set {payload = .getPhoneBattery(newValue)}
  }

  public var getWeather: VitalOSProtocol_GetWeatherRequest {
    get {
      if case .getWeather(let v)? = payload {return v}
      return VitalOSProtocol_GetWeatherRequest()
    }
    set {payload = .getWeather(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Payload: Equatable, Sendable {
    case getPhoneBattery(VitalOSProtocol_GetPhoneBatteryRequest)
    case getWeather(VitalOSProtocol_GetWeatherRequest)

  }

  public init() {}
}

//// A wrapper for any local message response sent FROM the phone TO the watch.
public struct VitalOSProtocol_LocalResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var payload: VitalOSProtocol_LocalResponse.OneOf_Payload? = nil

  public var getPhoneBattery: VitalOSProtocol_GetPhoneBatteryResponse {
    get {
      if case .getPhoneBattery(let v)? = payload {return v}
      return VitalOSProtocol_GetPhoneBatteryResponse()
    }
    set {payload = .getPhoneBattery(newValue)}
  }

  public var getWeather: VitalOSProtocol_GetWeatherResponse {
    get {
      if case .getWeather(let v)? = payload {return v}
      return VitalOSProtocol_GetWeatherResponse()
    }
    set {payload = .getWeather(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Payload: Equatable, Sendable {
    case getPhoneBattery(VitalOSProtocol_GetPhoneBatteryResponse)
    case getWeather(VitalOSProtocol_GetWeatherResponse)

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "VitalOSProtocol"

extension VitalOSProtocol_GetPhoneBatteryRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetPhoneBatteryRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_GetPhoneBatteryRequest, rhs: VitalOSProtocol_GetPhoneBatteryRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_GetPhoneBatteryResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetPhoneBatteryResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}level\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.level) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.level != 0 {
      try visitor.visitSingularInt32Field(value: self.level, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_GetPhoneBatteryResponse, rhs: VitalOSProtocol_GetPhoneBatteryResponse) -> Bool {
    if lhs.level != rhs.level {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_GetWeatherRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetWeatherRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_GetWeatherRequest, rhs: VitalOSProtocol_GetWeatherRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_GetWeatherResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetWeatherResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}latitude\0\u{1}longitude\0\u{1}elevation\0\u{3}generation_time_ms\0\u{3}utc_offset_ms\0\u{3}timestamp_ms\0\u{1}timezone\0\u{3}timezone_abbreviation\0\u{3}current_weather_data\0\u{3}daily_data_points\0\u{3}hourly_data_points\0")

  fileprivate class _StorageClass {
    var _latitude: Double = 0
    var _longitude: Double = 0
    var _elevation: Double = 0
    var _generationTimeMs: Int64 = 0
    var _utcOffsetMs: Int64 = 0
    var _timestampMs: Int64 = 0
    var _timezone: String = String()
    var _timezoneAbbreviation: String = String()
    var _currentWeatherData: VitalOSProtocol_CurrentWeatherData? = nil
    var _dailyDataPoints: [VitalOSProtocol_DailyWeatherData] = []
    var _hourlyDataPoints: [VitalOSProtocol_HourlyWeatherData] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _latitude = source._latitude
      _longitude = source._longitude
      _elevation = source._elevation
      _generationTimeMs = source._generationTimeMs
      _utcOffsetMs = source._utcOffsetMs
      _timestampMs = source._timestampMs
      _timezone = source._timezone
      _timezoneAbbreviation = source._timezoneAbbreviation
      _currentWeatherData = source._currentWeatherData
      _dailyDataPoints = source._dailyDataPoints
      _hourlyDataPoints = source._hourlyDataPoints
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularDoubleField(value: &_storage._latitude) }()
        case 2: try { try decoder.decodeSingularDoubleField(value: &_storage._longitude) }()
        case 3: try { try decoder.decodeSingularDoubleField(value: &_storage._elevation) }()
        case 4: try { try decoder.decodeSingularInt64Field(value: &_storage._generationTimeMs) }()
        case 5: try { try decoder.decodeSingularInt64Field(value: &_storage._utcOffsetMs) }()
        case 6: try { try decoder.decodeSingularInt64Field(value: &_storage._timestampMs) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._timezone) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._timezoneAbbreviation) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._currentWeatherData) }()
        case 10: try { try decoder.decodeRepeatedMessageField(value: &_storage._dailyDataPoints) }()
        case 11: try { try decoder.decodeRepeatedMessageField(value: &_storage._hourlyDataPoints) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._latitude.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._latitude, fieldNumber: 1)
      }
      if _storage._longitude.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._longitude, fieldNumber: 2)
      }
      if _storage._elevation.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._elevation, fieldNumber: 3)
      }
      if _storage._generationTimeMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._generationTimeMs, fieldNumber: 4)
      }
      if _storage._utcOffsetMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._utcOffsetMs, fieldNumber: 5)
      }
      if _storage._timestampMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._timestampMs, fieldNumber: 6)
      }
      if !_storage._timezone.isEmpty {
        try visitor.visitSingularStringField(value: _storage._timezone, fieldNumber: 7)
      }
      if !_storage._timezoneAbbreviation.isEmpty {
        try visitor.visitSingularStringField(value: _storage._timezoneAbbreviation, fieldNumber: 8)
      }
      try { if let v = _storage._currentWeatherData {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      if !_storage._dailyDataPoints.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._dailyDataPoints, fieldNumber: 10)
      }
      if !_storage._hourlyDataPoints.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._hourlyDataPoints, fieldNumber: 11)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_GetWeatherResponse, rhs: VitalOSProtocol_GetWeatherResponse) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._latitude != rhs_storage._latitude {return false}
        if _storage._longitude != rhs_storage._longitude {return false}
        if _storage._elevation != rhs_storage._elevation {return false}
        if _storage._generationTimeMs != rhs_storage._generationTimeMs {return false}
        if _storage._utcOffsetMs != rhs_storage._utcOffsetMs {return false}
        if _storage._timestampMs != rhs_storage._timestampMs {return false}
        if _storage._timezone != rhs_storage._timezone {return false}
        if _storage._timezoneAbbreviation != rhs_storage._timezoneAbbreviation {return false}
        if _storage._currentWeatherData != rhs_storage._currentWeatherData {return false}
        if _storage._dailyDataPoints != rhs_storage._dailyDataPoints {return false}
        if _storage._hourlyDataPoints != rhs_storage._hourlyDataPoints {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_CurrentWeatherData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CurrentWeatherData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}timestamp_ms\0\u{3}temperature_2m\0\u{3}relative_humidity_2m\0\u{3}weather_code\0\u{3}wind_speed_10m\0\u{3}wind_direction_10m\0\u{1}aqi\0\u{1}pm25\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.timestampMs) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.temperature2M) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.relativeHumidity2M) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.weatherCode) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.windSpeed10M) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self.windDirection10M) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.aqi) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self.pm25) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.timestampMs != 0 {
      try visitor.visitSingularInt64Field(value: self.timestampMs, fieldNumber: 1)
    }
    if self.temperature2M.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.temperature2M, fieldNumber: 2)
    }
    if self.relativeHumidity2M.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.relativeHumidity2M, fieldNumber: 3)
    }
    if self.weatherCode != 0 {
      try visitor.visitSingularInt32Field(value: self.weatherCode, fieldNumber: 4)
    }
    if self.windSpeed10M.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.windSpeed10M, fieldNumber: 5)
    }
    if self.windDirection10M.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.windDirection10M, fieldNumber: 6)
    }
    if self.aqi != 0 {
      try visitor.visitSingularInt32Field(value: self.aqi, fieldNumber: 7)
    }
    if self.pm25 != 0 {
      try visitor.visitSingularInt32Field(value: self.pm25, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_CurrentWeatherData, rhs: VitalOSProtocol_CurrentWeatherData) -> Bool {
    if lhs.timestampMs != rhs.timestampMs {return false}
    if lhs.temperature2M != rhs.temperature2M {return false}
    if lhs.relativeHumidity2M != rhs.relativeHumidity2M {return false}
    if lhs.weatherCode != rhs.weatherCode {return false}
    if lhs.windSpeed10M != rhs.windSpeed10M {return false}
    if lhs.windDirection10M != rhs.windDirection10M {return false}
    if lhs.aqi != rhs.aqi {return false}
    if lhs.pm25 != rhs.pm25 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_HourlyWeatherData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HourlyWeatherData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}timestamp_ms\0\u{3}temperature_2m\0\u{3}relative_humidity_2m\0\u{3}weather_code\0\u{1}visibility\0\u{3}wind_speed_10m\0\u{3}uv_index\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.timestampMs) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self.temperature2M) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.relativeHumidity2M) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.weatherCode) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self.visibility) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self.windSpeed10M) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self.uvIndex) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.timestampMs != 0 {
      try visitor.visitSingularInt64Field(value: self.timestampMs, fieldNumber: 1)
    }
    if self.temperature2M.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.temperature2M, fieldNumber: 2)
    }
    if self.relativeHumidity2M.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.relativeHumidity2M, fieldNumber: 3)
    }
    if self.weatherCode != 0 {
      try visitor.visitSingularInt32Field(value: self.weatherCode, fieldNumber: 4)
    }
    if self.visibility.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.visibility, fieldNumber: 5)
    }
    if self.windSpeed10M.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.windSpeed10M, fieldNumber: 6)
    }
    if self.uvIndex.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.uvIndex, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_HourlyWeatherData, rhs: VitalOSProtocol_HourlyWeatherData) -> Bool {
    if lhs.timestampMs != rhs.timestampMs {return false}
    if lhs.temperature2M != rhs.temperature2M {return false}
    if lhs.relativeHumidity2M != rhs.relativeHumidity2M {return false}
    if lhs.weatherCode != rhs.weatherCode {return false}
    if lhs.visibility != rhs.visibility {return false}
    if lhs.windSpeed10M != rhs.windSpeed10M {return false}
    if lhs.uvIndex != rhs.uvIndex {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_DailyWeatherData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DailyWeatherData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}timestamp_ms\0\u{3}weather_code\0\u{3}temperature_2m_max\0\u{3}temperature_2m_min\0\u{3}sunrise_ms\0\u{3}sunset_ms\0\u{3}precipitation_sum\0\u{3}uv_index_max\0\u{3}wind_speed_10m_max\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.timestampMs) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.weatherCode) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self.temperature2MMax) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self.temperature2MMin) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.sunriseMs) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.sunsetMs) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self.precipitationSum) }()
      case 8: try { try decoder.decodeSingularDoubleField(value: &self.uvIndexMax) }()
      case 9: try { try decoder.decodeSingularDoubleField(value: &self.windSpeed10MMax) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.timestampMs != 0 {
      try visitor.visitSingularInt64Field(value: self.timestampMs, fieldNumber: 1)
    }
    if self.weatherCode != 0 {
      try visitor.visitSingularInt32Field(value: self.weatherCode, fieldNumber: 2)
    }
    if self.temperature2MMax.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.temperature2MMax, fieldNumber: 3)
    }
    if self.temperature2MMin.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.temperature2MMin, fieldNumber: 4)
    }
    if self.sunriseMs != 0 {
      try visitor.visitSingularInt64Field(value: self.sunriseMs, fieldNumber: 5)
    }
    if self.sunsetMs != 0 {
      try visitor.visitSingularInt64Field(value: self.sunsetMs, fieldNumber: 6)
    }
    if self.precipitationSum.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.precipitationSum, fieldNumber: 7)
    }
    if self.uvIndexMax.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.uvIndexMax, fieldNumber: 8)
    }
    if self.windSpeed10MMax.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.windSpeed10MMax, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_DailyWeatherData, rhs: VitalOSProtocol_DailyWeatherData) -> Bool {
    if lhs.timestampMs != rhs.timestampMs {return false}
    if lhs.weatherCode != rhs.weatherCode {return false}
    if lhs.temperature2MMax != rhs.temperature2MMax {return false}
    if lhs.temperature2MMin != rhs.temperature2MMin {return false}
    if lhs.sunriseMs != rhs.sunriseMs {return false}
    if lhs.sunsetMs != rhs.sunsetMs {return false}
    if lhs.precipitationSum != rhs.precipitationSum {return false}
    if lhs.uvIndexMax != rhs.uvIndexMax {return false}
    if lhs.windSpeed10MMax != rhs.windSpeed10MMax {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_LocalRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LocalRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}get_phone_battery\0\u{3}get_weather\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: VitalOSProtocol_GetPhoneBatteryRequest?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getPhoneBattery(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getPhoneBattery(v)
        }
      }()
      case 2: try {
        var v: VitalOSProtocol_GetWeatherRequest?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getWeather(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getWeather(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.payload {
    case .getPhoneBattery?: try {
      guard case .getPhoneBattery(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .getWeather?: try {
      guard case .getWeather(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_LocalRequest, rhs: VitalOSProtocol_LocalRequest) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_LocalResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LocalResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}get_phone_battery\0\u{3}get_weather\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: VitalOSProtocol_GetPhoneBatteryResponse?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getPhoneBattery(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getPhoneBattery(v)
        }
      }()
      case 2: try {
        var v: VitalOSProtocol_GetWeatherResponse?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .getWeather(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .getWeather(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.payload {
    case .getPhoneBattery?: try {
      guard case .getPhoneBattery(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .getWeather?: try {
      guard case .getWeather(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_LocalResponse, rhs: VitalOSProtocol_LocalResponse) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
