// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: messaging.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Represents a standard REST API call.
public struct VitalOSProtocol_RestMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var method: VitalOSProtocol_RestMessage.Method = .get

  public var url: String = String()

  public var headers: Dictionary<String,String> = [:]

  public var body: Dictionary<String,String> = [:]

  public var useAppAuth: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum Method: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case get // = 0
    case post // = 1
    case put // = 2
    case delete // = 3
    case patch // = 4
    case UNRECOGNIZED(Int)

    public init() {
      self = .get
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .get
      case 1: self = .post
      case 2: self = .put
      case 3: self = .delete
      case 4: self = .patch
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .get: return 0
      case .post: return 1
      case .put: return 2
      case .delete: return 3
      case .patch: return 4
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [VitalOSProtocol_RestMessage.Method] = [
      .get,
      .post,
      .put,
      .delete,
      .patch,
    ]

  }

  public init() {}
}

/// Represents a local action on the phone.
/// This now contains a structured request instead of generic fields.
public struct VitalOSProtocol_LocalMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var request: VitalOSProtocol_LocalRequest {
    get {_request ?? VitalOSProtocol_LocalRequest()}
    set {_request = newValue}
  }
  /// Returns true if `request` has been explicitly set.
  public var hasRequest: Bool {self._request != nil}
  /// Clears the value of `request`. Subsequent reads from it will return its default value.
  public mutating func clearRequest() {self._request = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _request: VitalOSProtocol_LocalRequest? = nil
}

/// Raw data message
public struct VitalOSProtocol_RawMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var messageKey: String = String()

  public var payload: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A request initiated by the phone app to the watch app.
public struct VitalOSProtocol_PhoneRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var requestID: String = String()

  public var endpoint: String = String()

  public var payload: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A response from the watch back to the phone.
public struct VitalOSProtocol_WatchResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var originalRequestID: String = String()

  public var success: Bool = false

  public var payload: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A request initiated by the watch app to the phone app.
public struct VitalOSProtocol_WatchRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var requestID: String = String()

  public var requestType: VitalOSProtocol_WatchRequest.OneOf_RequestType? = nil

  public var local: VitalOSProtocol_LocalMessage {
    get {
      if case .local(let v)? = requestType {return v}
      return VitalOSProtocol_LocalMessage()
    }
    set {requestType = .local(newValue)}
  }

  public var rest: VitalOSProtocol_RestMessage {
    get {
      if case .rest(let v)? = requestType {return v}
      return VitalOSProtocol_RestMessage()
    }
    set {requestType = .rest(newValue)}
  }

  public var raw: VitalOSProtocol_RawMessage {
    get {
      if case .raw(let v)? = requestType {return v}
      return VitalOSProtocol_RawMessage()
    }
    set {requestType = .raw(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_RequestType: Equatable, Sendable {
    case local(VitalOSProtocol_LocalMessage)
    case rest(VitalOSProtocol_RestMessage)
    case raw(VitalOSProtocol_RawMessage)

  }

  public init() {}
}

//// Contains the metadata for a large payload that will be sent via a stream.
//// The device receives this, prepares for the stream, and sends back an ACK.
//// The app then initiates the stream using the standard streaming commands.
public struct VitalOSProtocol_StreamedPayloadInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: Int32 = 0

  public var totalSize: Int64 = 0

  /// File path where streamed data was written (watch-side)
  /// Present in final response after stream completes
  public var filePath: String = String()

  /// Content type of the response (e.g., "application/json", "image/jpeg")
  public var contentType: String = String()

  /// Original HTTP status code from the API response
  public var httpStatusCode: Int32 = 0

  /// Response headers for metadata (optional)
  public var responseHeaders: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

//// to a WatchRequest.
public struct VitalOSProtocol_PhoneResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The ID from the original WatchRequest this is responding to.
  public var originalRequestID: String = String()

  /// Standard status fields.
  public var success: Bool = false

  /// Corresponds to your ErrorCode enum
  public var errorCode: Int32 = 0

  public var errorMessage: String = String()

  /// The payload of the response. It will be one of these two types.
  public var payload: VitalOSProtocol_PhoneResponse.OneOf_Payload? = nil

  /// For small responses, the data is sent directly.
  public var directPayload: Data {
    get {
      if case .directPayload(let v)? = payload {return v}
      return Data()
    }
    set {payload = .directPayload(newValue)}
  }

  /// For large responses, this provides the metadata for an upcoming stream.
  public var streamedPayload: VitalOSProtocol_StreamedPayloadInfo {
    get {
      if case .streamedPayload(let v)? = payload {return v}
      return VitalOSProtocol_StreamedPayloadInfo()
    }
    set {payload = .streamedPayload(newValue)}
  }

  public var localResponse: VitalOSProtocol_LocalResponse {
    get {
      if case .localResponse(let v)? = payload {return v}
      return VitalOSProtocol_LocalResponse()
    }
    set {payload = .localResponse(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The payload of the response. It will be one of these two types.
  public enum OneOf_Payload: Equatable, Sendable {
    /// For small responses, the data is sent directly.
    case directPayload(Data)
    /// For large responses, this provides the metadata for an upcoming stream.
    case streamedPayload(VitalOSProtocol_StreamedPayloadInfo)
    case localResponse(VitalOSProtocol_LocalResponse)

  }

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "VitalOSProtocol"

extension VitalOSProtocol_RestMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RestMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}method\0\u{1}url\0\u{1}headers\0\u{1}body\0\u{3}use_app_auth\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.method) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.headers) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.body) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.useAppAuth) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.method != .get {
      try visitor.visitSingularEnumField(value: self.method, fieldNumber: 1)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 2)
    }
    if !self.headers.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.headers, fieldNumber: 3)
    }
    if !self.body.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.body, fieldNumber: 4)
    }
    if self.useAppAuth != false {
      try visitor.visitSingularBoolField(value: self.useAppAuth, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_RestMessage, rhs: VitalOSProtocol_RestMessage) -> Bool {
    if lhs.method != rhs.method {return false}
    if lhs.url != rhs.url {return false}
    if lhs.headers != rhs.headers {return false}
    if lhs.body != rhs.body {return false}
    if lhs.useAppAuth != rhs.useAppAuth {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_RestMessage.Method: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0GET\0\u{1}POST\0\u{1}PUT\0\u{1}DELETE\0\u{1}PATCH\0")
}

extension VitalOSProtocol_LocalMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".LocalMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}request\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._request) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._request {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_LocalMessage, rhs: VitalOSProtocol_LocalMessage) -> Bool {
    if lhs._request != rhs._request {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_RawMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RawMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}message_key\0\u{1}payload\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.messageKey) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.payload) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.messageKey.isEmpty {
      try visitor.visitSingularStringField(value: self.messageKey, fieldNumber: 1)
    }
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_RawMessage, rhs: VitalOSProtocol_RawMessage) -> Bool {
    if lhs.messageKey != rhs.messageKey {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_PhoneRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PhoneRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{1}endpoint\0\u{1}payload\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.endpoint) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.payload) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    if !self.endpoint.isEmpty {
      try visitor.visitSingularStringField(value: self.endpoint, fieldNumber: 2)
    }
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_PhoneRequest, rhs: VitalOSProtocol_PhoneRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.endpoint != rhs.endpoint {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_WatchResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WatchResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}original_request_id\0\u{1}success\0\u{1}payload\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.originalRequestID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.payload) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.originalRequestID.isEmpty {
      try visitor.visitSingularStringField(value: self.originalRequestID, fieldNumber: 1)
    }
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 2)
    }
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_WatchResponse, rhs: VitalOSProtocol_WatchResponse) -> Bool {
    if lhs.originalRequestID != rhs.originalRequestID {return false}
    if lhs.success != rhs.success {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_WatchRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WatchRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{2}\u{2}local\0\u{1}rest\0\u{1}raw\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 3: try {
        var v: VitalOSProtocol_LocalMessage?
        var hadOneofValue = false
        if let current = self.requestType {
          hadOneofValue = true
          if case .local(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.requestType = .local(v)
        }
      }()
      case 4: try {
        var v: VitalOSProtocol_RestMessage?
        var hadOneofValue = false
        if let current = self.requestType {
          hadOneofValue = true
          if case .rest(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.requestType = .rest(v)
        }
      }()
      case 5: try {
        var v: VitalOSProtocol_RawMessage?
        var hadOneofValue = false
        if let current = self.requestType {
          hadOneofValue = true
          if case .raw(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.requestType = .raw(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    switch self.requestType {
    case .local?: try {
      guard case .local(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .rest?: try {
      guard case .rest(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .raw?: try {
      guard case .raw(let v)? = self.requestType else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_WatchRequest, rhs: VitalOSProtocol_WatchRequest) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.requestType != rhs.requestType {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_StreamedPayloadInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamedPayloadInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{3}total_size\0\u{3}file_path\0\u{3}content_type\0\u{3}http_status_code\0\u{3}response_headers\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.totalSize) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.filePath) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.contentType) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.httpStatusCode) }()
      case 6: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.responseHeaders) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularInt32Field(value: self.streamID, fieldNumber: 1)
    }
    if self.totalSize != 0 {
      try visitor.visitSingularInt64Field(value: self.totalSize, fieldNumber: 2)
    }
    if !self.filePath.isEmpty {
      try visitor.visitSingularStringField(value: self.filePath, fieldNumber: 3)
    }
    if !self.contentType.isEmpty {
      try visitor.visitSingularStringField(value: self.contentType, fieldNumber: 4)
    }
    if self.httpStatusCode != 0 {
      try visitor.visitSingularInt32Field(value: self.httpStatusCode, fieldNumber: 5)
    }
    if !self.responseHeaders.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.responseHeaders, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_StreamedPayloadInfo, rhs: VitalOSProtocol_StreamedPayloadInfo) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.totalSize != rhs.totalSize {return false}
    if lhs.filePath != rhs.filePath {return false}
    if lhs.contentType != rhs.contentType {return false}
    if lhs.httpStatusCode != rhs.httpStatusCode {return false}
    if lhs.responseHeaders != rhs.responseHeaders {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_PhoneResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PhoneResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}original_request_id\0\u{1}success\0\u{3}error_code\0\u{3}error_message\0\u{4}\u{6}direct_payload\0\u{3}streamed_payload\0\u{3}local_response\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.originalRequestID) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.errorCode) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.errorMessage) }()
      case 10: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.payload != nil {try decoder.handleConflictingOneOf()}
          self.payload = .directPayload(v)
        }
      }()
      case 11: try {
        var v: VitalOSProtocol_StreamedPayloadInfo?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .streamedPayload(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .streamedPayload(v)
        }
      }()
      case 12: try {
        var v: VitalOSProtocol_LocalResponse?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .localResponse(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .localResponse(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.originalRequestID.isEmpty {
      try visitor.visitSingularStringField(value: self.originalRequestID, fieldNumber: 1)
    }
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 2)
    }
    if self.errorCode != 0 {
      try visitor.visitSingularInt32Field(value: self.errorCode, fieldNumber: 3)
    }
    if !self.errorMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.errorMessage, fieldNumber: 4)
    }
    switch self.payload {
    case .directPayload?: try {
      guard case .directPayload(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 10)
    }()
    case .streamedPayload?: try {
      guard case .streamedPayload(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    }()
    case .localResponse?: try {
      guard case .localResponse(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_PhoneResponse, rhs: VitalOSProtocol_PhoneResponse) -> Bool {
    if lhs.originalRequestID != rhs.originalRequestID {return false}
    if lhs.success != rhs.success {return false}
    if lhs.errorCode != rhs.errorCode {return false}
    if lhs.errorMessage != rhs.errorMessage {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
