// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: settings_configuration.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// The top-level configuration.
/// It contains flat lists of all available settings.
public struct VitalOSProtocol_SettingsConfiguration: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The client app will use these lists to construct the UI.
  public var allSettings: [VitalOSProtocol_SettingsEntry] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Defines a single setting.
public struct VitalOSProtocol_SettingsEntry: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unique identifier, e.g., "brightness_setting"
  public var settingID: String = String()

  /// Text shown on screen, e.g., "Brightness"
  public var displayName: String = String()

  /// The UI control to render
  public var type: VitalOSProtocol_SettingsEntry.SettingType = .unspecified

  /// A list of group IDs where this setting should be displayed.
  public var groupIds: [String] = []

  public var value: VitalOSProtocol_SettingsEntry.OneOf_Value? = nil

  public var boolValue: Bool {
    get {
      if case .boolValue(let v)? = value {return v}
      return false
    }
    set {value = .boolValue(newValue)}
  }

  public var intValue: Int32 {
    get {
      if case .intValue(let v)? = value {return v}
      return 0
    }
    set {value = .intValue(newValue)}
  }

  public var stringValue: String {
    get {
      if case .stringValue(let v)? = value {return v}
      return String()
    }
    set {value = .stringValue(newValue)}
  }

  public var enumOptions: [String] = []

  public var minValue: Int32 = 0

  public var maxValue: Int32 = 0

  public var isRequired: Bool = false

  public var interval: Int32 = 0

  public var iconPath: String = String()

  public var isEnabled: Bool = false

  public var isHidden: Bool = false

  public var lastUpdated: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Value: Equatable, Sendable {
    case boolValue(Bool)
    case intValue(Int32)
    case stringValue(String)

  }

  public enum SettingType: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case unspecified // = 0
    case toggle // = 1
    case `enum` // = 2
    case range // = 3
    case custom // = 4
    case button // = 5
    case info // = 6
    case group // = 7
    case UNRECOGNIZED(Int)

    public init() {
      self = .unspecified
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .toggle
      case 2: self = .enum
      case 3: self = .range
      case 4: self = .custom
      case 5: self = .button
      case 6: self = .info
      case 7: self = .group
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .toggle: return 1
      case .enum: return 2
      case .range: return 3
      case .custom: return 4
      case .button: return 5
      case .info: return 6
      case .group: return 7
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [VitalOSProtocol_SettingsEntry.SettingType] = [
      .unspecified,
      .toggle,
      .enum,
      .range,
      .custom,
      .button,
      .info,
      .group,
    ]

  }

  public init() {}
}

public struct VitalOSProtocol_SettingsValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unique identifier for the setting being updated, e.g., "brightness"
  public var settingID: String = String()

  /// The updated value for the setting. Uses a oneof to support different data types.
  public var value: VitalOSProtocol_SettingsValue.OneOf_Value? = nil

  /// For boolean settings (e.g., TOGGLE type)
  public var boolValue: Bool {
    get {
      if case .boolValue(let v)? = value {return v}
      return false
    }
    set {value = .boolValue(newValue)}
  }

  /// For integer settings (e.g., brightness level, enum index)
  public var intValue: Int32 {
    get {
      if case .intValue(let v)? = value {return v}
      return 0
    }
    set {value = .intValue(newValue)}
  }

  /// For string settings (e.g., text inputs)
  public var stringValue: String {
    get {
      if case .stringValue(let v)? = value {return v}
      return String()
    }
    set {value = .stringValue(newValue)}
  }

  public var lastUpdated: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The updated value for the setting. Uses a oneof to support different data types.
  public enum OneOf_Value: Equatable, Sendable {
    /// For boolean settings (e.g., TOGGLE type)
    case boolValue(Bool)
    /// For integer settings (e.g., brightness level, enum index)
    case intValue(Int32)
    /// For string settings (e.g., text inputs)
    case stringValue(String)

  }

  public init() {}
}

public struct VitalOSProtocol_GetUpdatedSettingsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sinceTimestamp: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VitalOSProtocol_GetUpdatedSettingsResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var updatedEntries: [VitalOSProtocol_SettingsEntry] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VitalOSProtocol_GetUpdatedValuesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var sinceTimestamp: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VitalOSProtocol_GetUpdatedValuesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var updatedValues: [VitalOSProtocol_SettingsValue] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "VitalOSProtocol"

extension VitalOSProtocol_SettingsConfiguration: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SettingsConfiguration"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}all_settings\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.allSettings) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.allSettings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.allSettings, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_SettingsConfiguration, rhs: VitalOSProtocol_SettingsConfiguration) -> Bool {
    if lhs.allSettings != rhs.allSettings {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_SettingsEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SettingsEntry"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}setting_id\0\u{3}display_name\0\u{1}type\0\u{3}group_ids\0\u{3}bool_value\0\u{3}int_value\0\u{3}string_value\0\u{3}enum_options\0\u{3}min_value\0\u{3}max_value\0\u{3}is_required\0\u{1}interval\0\u{3}icon_path\0\u{3}is_enabled\0\u{3}is_hidden\0\u{3}last_updated\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.settingID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.displayName) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      case 4: try { try decoder.decodeRepeatedStringField(value: &self.groupIds) }()
      case 5: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .boolValue(v)
        }
      }()
      case 6: try {
        var v: Int32?
        try decoder.decodeSingularInt32Field(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .intValue(v)
        }
      }()
      case 7: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .stringValue(v)
        }
      }()
      case 8: try { try decoder.decodeRepeatedStringField(value: &self.enumOptions) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self.minValue) }()
      case 10: try { try decoder.decodeSingularInt32Field(value: &self.maxValue) }()
      case 11: try { try decoder.decodeSingularBoolField(value: &self.isRequired) }()
      case 12: try { try decoder.decodeSingularInt32Field(value: &self.interval) }()
      case 13: try { try decoder.decodeSingularStringField(value: &self.iconPath) }()
      case 14: try { try decoder.decodeSingularBoolField(value: &self.isEnabled) }()
      case 15: try { try decoder.decodeSingularBoolField(value: &self.isHidden) }()
      case 16: try { try decoder.decodeSingularInt64Field(value: &self.lastUpdated) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.settingID.isEmpty {
      try visitor.visitSingularStringField(value: self.settingID, fieldNumber: 1)
    }
    if !self.displayName.isEmpty {
      try visitor.visitSingularStringField(value: self.displayName, fieldNumber: 2)
    }
    if self.type != .unspecified {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 3)
    }
    if !self.groupIds.isEmpty {
      try visitor.visitRepeatedStringField(value: self.groupIds, fieldNumber: 4)
    }
    switch self.value {
    case .boolValue?: try {
      guard case .boolValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    }()
    case .intValue?: try {
      guard case .intValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 6)
    }()
    case .stringValue?: try {
      guard case .stringValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    }()
    case nil: break
    }
    if !self.enumOptions.isEmpty {
      try visitor.visitRepeatedStringField(value: self.enumOptions, fieldNumber: 8)
    }
    if self.minValue != 0 {
      try visitor.visitSingularInt32Field(value: self.minValue, fieldNumber: 9)
    }
    if self.maxValue != 0 {
      try visitor.visitSingularInt32Field(value: self.maxValue, fieldNumber: 10)
    }
    if self.isRequired != false {
      try visitor.visitSingularBoolField(value: self.isRequired, fieldNumber: 11)
    }
    if self.interval != 0 {
      try visitor.visitSingularInt32Field(value: self.interval, fieldNumber: 12)
    }
    if !self.iconPath.isEmpty {
      try visitor.visitSingularStringField(value: self.iconPath, fieldNumber: 13)
    }
    if self.isEnabled != false {
      try visitor.visitSingularBoolField(value: self.isEnabled, fieldNumber: 14)
    }
    if self.isHidden != false {
      try visitor.visitSingularBoolField(value: self.isHidden, fieldNumber: 15)
    }
    if self.lastUpdated != 0 {
      try visitor.visitSingularInt64Field(value: self.lastUpdated, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_SettingsEntry, rhs: VitalOSProtocol_SettingsEntry) -> Bool {
    if lhs.settingID != rhs.settingID {return false}
    if lhs.displayName != rhs.displayName {return false}
    if lhs.type != rhs.type {return false}
    if lhs.groupIds != rhs.groupIds {return false}
    if lhs.value != rhs.value {return false}
    if lhs.enumOptions != rhs.enumOptions {return false}
    if lhs.minValue != rhs.minValue {return false}
    if lhs.maxValue != rhs.maxValue {return false}
    if lhs.isRequired != rhs.isRequired {return false}
    if lhs.interval != rhs.interval {return false}
    if lhs.iconPath != rhs.iconPath {return false}
    if lhs.isEnabled != rhs.isEnabled {return false}
    if lhs.isHidden != rhs.isHidden {return false}
    if lhs.lastUpdated != rhs.lastUpdated {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_SettingsEntry.SettingType: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0SETTING_TYPE_UNSPECIFIED\0\u{1}TOGGLE\0\u{1}ENUM\0\u{1}RANGE\0\u{1}CUSTOM\0\u{1}BUTTON\0\u{1}INFO\0\u{1}GROUP\0")
}

extension VitalOSProtocol_SettingsValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SettingsValue"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}setting_id\0\u{3}bool_value\0\u{3}int_value\0\u{3}string_value\0\u{3}last_updated\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.settingID) }()
      case 2: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .boolValue(v)
        }
      }()
      case 3: try {
        var v: Int32?
        try decoder.decodeSingularInt32Field(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .intValue(v)
        }
      }()
      case 4: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .stringValue(v)
        }
      }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.lastUpdated) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.settingID.isEmpty {
      try visitor.visitSingularStringField(value: self.settingID, fieldNumber: 1)
    }
    switch self.value {
    case .boolValue?: try {
      guard case .boolValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    }()
    case .intValue?: try {
      guard case .intValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    }()
    case .stringValue?: try {
      guard case .stringValue(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    if self.lastUpdated != 0 {
      try visitor.visitSingularInt64Field(value: self.lastUpdated, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_SettingsValue, rhs: VitalOSProtocol_SettingsValue) -> Bool {
    if lhs.settingID != rhs.settingID {return false}
    if lhs.value != rhs.value {return false}
    if lhs.lastUpdated != rhs.lastUpdated {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_GetUpdatedSettingsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetUpdatedSettingsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}since_timestamp\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.sinceTimestamp) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.sinceTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.sinceTimestamp, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_GetUpdatedSettingsRequest, rhs: VitalOSProtocol_GetUpdatedSettingsRequest) -> Bool {
    if lhs.sinceTimestamp != rhs.sinceTimestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_GetUpdatedSettingsResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetUpdatedSettingsResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}updated_entries\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.updatedEntries) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.updatedEntries.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.updatedEntries, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_GetUpdatedSettingsResponse, rhs: VitalOSProtocol_GetUpdatedSettingsResponse) -> Bool {
    if lhs.updatedEntries != rhs.updatedEntries {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_GetUpdatedValuesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetUpdatedValuesRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}since_timestamp\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.sinceTimestamp) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.sinceTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.sinceTimestamp, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_GetUpdatedValuesRequest, rhs: VitalOSProtocol_GetUpdatedValuesRequest) -> Bool {
    if lhs.sinceTimestamp != rhs.sinceTimestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_GetUpdatedValuesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetUpdatedValuesResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}updated_values\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.updatedValues) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.updatedValues.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.updatedValues, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_GetUpdatedValuesResponse, rhs: VitalOSProtocol_GetUpdatedValuesResponse) -> Bool {
    if lhs.updatedValues != rhs.updatedValues {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
