// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: sleep.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum VitalOSProtocol_SleepStage: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case awake // = 0
  case light // = 1
  case deep // = 2
  case rem // = 3
  case UNRECOGNIZED(Int)

  public init() {
    self = .awake
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .awake
    case 1: self = .light
    case 2: self = .deep
    case 3: self = .rem
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .awake: return 0
    case .light: return 1
    case .deep: return 2
    case .rem: return 3
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VitalOSProtocol_SleepStage] = [
    .awake,
    .light,
    .deep,
    .rem,
  ]

}

public struct VitalOSProtocol_SleepSyncRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unix timestamp (ms) inclusive
  public var startTimestamp: Int64 = 0

  /// Unix timestamp (ms) exclusive
  public var endTimestamp: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VitalOSProtocol_SleepUpdatedSinceRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Unix ms; return days where updated_at_ts >= this
  public var updatedSinceTs: Int64 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A single derived sleep segment (for timeline rendering).
public struct VitalOSProtocol_SleepSegment: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var startTimestamp: Int64 = 0

  public var endTimestamp: Int64 = 0

  public var stage: VitalOSProtocol_SleepStage = .awake

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Lightweight summary for quick queries (weekly charts, BLE sync).
/// Can be used without loading full segments/naps.
/// All total_sleep_ms / light_ms / deep_ms / rem_ms / awake_ms are for MAIN SLEEP ONLY.
/// Nap totals are separate (nap_total_sleep_ms and nap stage breakdown).
public struct VitalOSProtocol_SleepDaySummary: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var dayStartTs: Int64 {
    get {_storage._dayStartTs}
    set {_uniqueStorage()._dayStartTs = newValue}
  }

  public var dayEndTs: Int64 {
    get {_storage._dayEndTs}
    set {_uniqueStorage()._dayEndTs = newValue}
  }

  public var updatedAtTs: Int64 {
    get {_storage._updatedAtTs}
    set {_uniqueStorage()._updatedAtTs = newValue}
  }

  public var timezoneOffsetSeconds: Int32 {
    get {_storage._timezoneOffsetSeconds}
    set {_uniqueStorage()._timezoneOffsetSeconds = newValue}
  }

  public var mainSleepIndex: Int32 {
    get {_storage._mainSleepIndex}
    set {_uniqueStorage()._mainSleepIndex = newValue}
  }

  public var mainSleepStartTs: Int64 {
    get {_storage._mainSleepStartTs}
    set {_uniqueStorage()._mainSleepStartTs = newValue}
  }

  public var mainSleepEndTs: Int64 {
    get {_storage._mainSleepEndTs}
    set {_uniqueStorage()._mainSleepEndTs = newValue}
  }

  /// Main sleep only: time in bed (including awake intervals)
  public var totalSleepMs: Int64 {
    get {_storage._totalSleepMs}
    set {_uniqueStorage()._totalSleepMs = newValue}
  }

  /// Main sleep only
  public var lightMs: Int64 {
    get {_storage._lightMs}
    set {_uniqueStorage()._lightMs = newValue}
  }

  /// Main sleep only
  public var deepMs: Int64 {
    get {_storage._deepMs}
    set {_uniqueStorage()._deepMs = newValue}
  }

  /// Main sleep only
  public var remMs: Int64 {
    get {_storage._remMs}
    set {_uniqueStorage()._remMs = newValue}
  }

  /// Main sleep only: awake in bed during main sleep
  public var awakeMs: Int64 {
    get {_storage._awakeMs}
    set {_uniqueStorage()._awakeMs = newValue}
  }

  public var eligibleSleepCount: Int32 {
    get {_storage._eligibleSleepCount}
    set {_uniqueStorage()._eligibleSleepCount = newValue}
  }

  /// Timezone ID (e.g., "GMT", "Europe/London", "America/New_York")
  public var timezoneID: String {
    get {_storage._timezoneID}
    set {_uniqueStorage()._timezoneID = newValue}
  }

  /// Nap totals (sum across all naps for the day)
  public var napTotalSleepMs: Int64 {
    get {_storage._napTotalSleepMs}
    set {_uniqueStorage()._napTotalSleepMs = newValue}
  }

  public var napLightMs: Int64 {
    get {_storage._napLightMs}
    set {_uniqueStorage()._napLightMs = newValue}
  }

  public var napDeepMs: Int64 {
    get {_storage._napDeepMs}
    set {_uniqueStorage()._napDeepMs = newValue}
  }

  public var napRemMs: Int64 {
    get {_storage._napRemMs}
    set {_uniqueStorage()._napRemMs = newValue}
  }

  public var napAwakeMs: Int64 {
    get {_storage._napAwakeMs}
    set {_uniqueStorage()._napAwakeMs = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Per-day sleep artifact. One file per calendar day (wake-up day / midnight boundary).
/// Continuously overwritten for current day; immutable for past days.
/// Segments carry real event timestamps — no synthetic bucket-splitting.
public struct VitalOSProtocol_SleepDay: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var summary: VitalOSProtocol_SleepDaySummary {
    get {_summary ?? VitalOSProtocol_SleepDaySummary()}
    set {_summary = newValue}
  }
  /// Returns true if `summary` has been explicitly set.
  public var hasSummary: Bool {self._summary != nil}
  /// Clears the value of `summary`. Subsequent reads from it will return its default value.
  public mutating func clearSummary() {self._summary = nil}

  /// Ordered real-timestamp segments for the main (longest/merged) sleep session.
  /// Boundaries come from summary.main_sleep_start_ts / main_sleep_end_ts.
  public var mainSleepSegments: [VitalOSProtocol_SleepSegment] = []

  public var naps: [VitalOSProtocol_SleepDay.Nap] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct Nap: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Ordered real-timestamp segments for this nap.
    public var segments: [VitalOSProtocol_SleepSegment] = []

    /// Actual ENTER / EXIT times for this nap session.
    public var startTimestamp: Int64 = 0

    public var endTimestamp: Int64 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}

  fileprivate var _summary: VitalOSProtocol_SleepDaySummary? = nil
}

public struct VitalOSProtocol_SleepDaySyncPayload: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var day: VitalOSProtocol_SleepDay {
    get {_day ?? VitalOSProtocol_SleepDay()}
    set {_day = newValue}
  }
  /// Returns true if `day` has been explicitly set.
  public var hasDay: Bool {self._day != nil}
  /// Clears the value of `day`. Subsequent reads from it will return its default value.
  public mutating func clearDay() {self._day = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _day: VitalOSProtocol_SleepDay? = nil
}

/// Watch -> App: bulk sync response (one command ID; oneof distinguishes day vs terminal complete).
public struct VitalOSProtocol_SleepSyncComplete: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VitalOSProtocol_SleepSyncNotification: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var payload: VitalOSProtocol_SleepSyncNotification.OneOf_Payload? = nil

  public var data: VitalOSProtocol_SleepDaySyncPayload {
    get {
      if case .data(let v)? = payload {return v}
      return VitalOSProtocol_SleepDaySyncPayload()
    }
    set {payload = .data(newValue)}
  }

  public var complete: VitalOSProtocol_SleepSyncComplete {
    get {
      if case .complete(let v)? = payload {return v}
      return VitalOSProtocol_SleepSyncComplete()
    }
    set {payload = .complete(newValue)}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum OneOf_Payload: Equatable, Sendable {
    case data(VitalOSProtocol_SleepDaySyncPayload)
    case complete(VitalOSProtocol_SleepSyncComplete)

  }

  public init() {}
}

/// A single raw stage-transition event recorded during an in-progress session.
/// stage is the stage we transitioned INTO at timestamp_ms.
public struct VitalOSProtocol_RawStageChange: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var timestampMs: Int64 = 0

  public var stage: VitalOSProtocol_SleepStage = .awake

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// In-progress sleep session state for recovery after reboot.
/// Persisted only when a sleep session is active; deleted when sleep completes.
public struct VitalOSProtocol_CurrentSleepSessionState: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Calendar day this session belongs to
  public var dayStartMs: Int64 = 0

  /// When ENTER occurred
  public var sessionStartMs: Int64 = 0

  /// Timestamp of most recent stage transition
  public var lastStageChangeMs: Int64 = 0

  /// Current stage we're in
  public var currentStage: VitalOSProtocol_SleepStage = .awake

  /// Light sleep duration so far
  public var accumulatedLightMs: Int64 = 0

  /// Deep sleep duration so far
  public var accumulatedDeepMs: Int64 = 0

  /// REM sleep duration so far
  public var accumulatedRemMs: Int64 = 0

  /// Awake duration so far
  public var accumulatedAwakeMs: Int64 = 0

  /// Full ordered list of stage transitions (ENTER implicit at session_start_ms with LIGHT).
  /// Used to reconstruct real-timestamp SleepSegment list after reboot.
  public var stageChanges: [VitalOSProtocol_RawStageChange] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VitalOSProtocol_SleepDataNotification: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Day identifier (start of day in millis)
  public var dayTimestamp: Int64 = 0

  /// Main sleep session finished for the day
  public var isMainSleepComplete: Bool = false

  /// Sleep file identifier/path
  public var filename: String = String()

  /// Total sleep duration in minutes
  public var totalSleepMinutes: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "VitalOSProtocol"

extension VitalOSProtocol_SleepStage: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0AWAKE\0\u{1}LIGHT\0\u{1}DEEP\0\u{1}REM\0")
}

extension VitalOSProtocol_SleepSyncRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SleepSyncRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}start_timestamp\0\u{3}end_timestamp\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.startTimestamp) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.endTimestamp) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.startTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.startTimestamp, fieldNumber: 1)
    }
    if self.endTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.endTimestamp, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_SleepSyncRequest, rhs: VitalOSProtocol_SleepSyncRequest) -> Bool {
    if lhs.startTimestamp != rhs.startTimestamp {return false}
    if lhs.endTimestamp != rhs.endTimestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_SleepUpdatedSinceRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SleepUpdatedSinceRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}updated_since_ts\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.updatedSinceTs) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.updatedSinceTs != 0 {
      try visitor.visitSingularInt64Field(value: self.updatedSinceTs, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_SleepUpdatedSinceRequest, rhs: VitalOSProtocol_SleepUpdatedSinceRequest) -> Bool {
    if lhs.updatedSinceTs != rhs.updatedSinceTs {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_SleepSegment: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SleepSegment"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}start_timestamp\0\u{3}end_timestamp\0\u{1}stage\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.startTimestamp) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.endTimestamp) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.stage) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.startTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.startTimestamp, fieldNumber: 1)
    }
    if self.endTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.endTimestamp, fieldNumber: 2)
    }
    if self.stage != .awake {
      try visitor.visitSingularEnumField(value: self.stage, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_SleepSegment, rhs: VitalOSProtocol_SleepSegment) -> Bool {
    if lhs.startTimestamp != rhs.startTimestamp {return false}
    if lhs.endTimestamp != rhs.endTimestamp {return false}
    if lhs.stage != rhs.stage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_SleepDaySummary: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SleepDaySummary"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}day_start_ts\0\u{3}day_end_ts\0\u{3}updated_at_ts\0\u{3}timezone_offset_seconds\0\u{3}main_sleep_index\0\u{3}main_sleep_start_ts\0\u{3}main_sleep_end_ts\0\u{3}total_sleep_ms\0\u{3}light_ms\0\u{3}deep_ms\0\u{3}rem_ms\0\u{3}awake_ms\0\u{3}eligible_sleep_count\0\u{3}timezone_id\0\u{3}nap_total_sleep_ms\0\u{3}nap_light_ms\0\u{3}nap_deep_ms\0\u{3}nap_rem_ms\0\u{3}nap_awake_ms\0")

  fileprivate class _StorageClass {
    var _dayStartTs: Int64 = 0
    var _dayEndTs: Int64 = 0
    var _updatedAtTs: Int64 = 0
    var _timezoneOffsetSeconds: Int32 = 0
    var _mainSleepIndex: Int32 = 0
    var _mainSleepStartTs: Int64 = 0
    var _mainSleepEndTs: Int64 = 0
    var _totalSleepMs: Int64 = 0
    var _lightMs: Int64 = 0
    var _deepMs: Int64 = 0
    var _remMs: Int64 = 0
    var _awakeMs: Int64 = 0
    var _eligibleSleepCount: Int32 = 0
    var _timezoneID: String = String()
    var _napTotalSleepMs: Int64 = 0
    var _napLightMs: Int64 = 0
    var _napDeepMs: Int64 = 0
    var _napRemMs: Int64 = 0
    var _napAwakeMs: Int64 = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _dayStartTs = source._dayStartTs
      _dayEndTs = source._dayEndTs
      _updatedAtTs = source._updatedAtTs
      _timezoneOffsetSeconds = source._timezoneOffsetSeconds
      _mainSleepIndex = source._mainSleepIndex
      _mainSleepStartTs = source._mainSleepStartTs
      _mainSleepEndTs = source._mainSleepEndTs
      _totalSleepMs = source._totalSleepMs
      _lightMs = source._lightMs
      _deepMs = source._deepMs
      _remMs = source._remMs
      _awakeMs = source._awakeMs
      _eligibleSleepCount = source._eligibleSleepCount
      _timezoneID = source._timezoneID
      _napTotalSleepMs = source._napTotalSleepMs
      _napLightMs = source._napLightMs
      _napDeepMs = source._napDeepMs
      _napRemMs = source._napRemMs
      _napAwakeMs = source._napAwakeMs
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt64Field(value: &_storage._dayStartTs) }()
        case 2: try { try decoder.decodeSingularInt64Field(value: &_storage._dayEndTs) }()
        case 3: try { try decoder.decodeSingularInt64Field(value: &_storage._updatedAtTs) }()
        case 4: try { try decoder.decodeSingularInt32Field(value: &_storage._timezoneOffsetSeconds) }()
        case 5: try { try decoder.decodeSingularInt32Field(value: &_storage._mainSleepIndex) }()
        case 6: try { try decoder.decodeSingularInt64Field(value: &_storage._mainSleepStartTs) }()
        case 7: try { try decoder.decodeSingularInt64Field(value: &_storage._mainSleepEndTs) }()
        case 8: try { try decoder.decodeSingularInt64Field(value: &_storage._totalSleepMs) }()
        case 9: try { try decoder.decodeSingularInt64Field(value: &_storage._lightMs) }()
        case 10: try { try decoder.decodeSingularInt64Field(value: &_storage._deepMs) }()
        case 11: try { try decoder.decodeSingularInt64Field(value: &_storage._remMs) }()
        case 12: try { try decoder.decodeSingularInt64Field(value: &_storage._awakeMs) }()
        case 13: try { try decoder.decodeSingularInt32Field(value: &_storage._eligibleSleepCount) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._timezoneID) }()
        case 15: try { try decoder.decodeSingularInt64Field(value: &_storage._napTotalSleepMs) }()
        case 16: try { try decoder.decodeSingularInt64Field(value: &_storage._napLightMs) }()
        case 17: try { try decoder.decodeSingularInt64Field(value: &_storage._napDeepMs) }()
        case 18: try { try decoder.decodeSingularInt64Field(value: &_storage._napRemMs) }()
        case 19: try { try decoder.decodeSingularInt64Field(value: &_storage._napAwakeMs) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._dayStartTs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._dayStartTs, fieldNumber: 1)
      }
      if _storage._dayEndTs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._dayEndTs, fieldNumber: 2)
      }
      if _storage._updatedAtTs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._updatedAtTs, fieldNumber: 3)
      }
      if _storage._timezoneOffsetSeconds != 0 {
        try visitor.visitSingularInt32Field(value: _storage._timezoneOffsetSeconds, fieldNumber: 4)
      }
      if _storage._mainSleepIndex != 0 {
        try visitor.visitSingularInt32Field(value: _storage._mainSleepIndex, fieldNumber: 5)
      }
      if _storage._mainSleepStartTs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._mainSleepStartTs, fieldNumber: 6)
      }
      if _storage._mainSleepEndTs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._mainSleepEndTs, fieldNumber: 7)
      }
      if _storage._totalSleepMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._totalSleepMs, fieldNumber: 8)
      }
      if _storage._lightMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._lightMs, fieldNumber: 9)
      }
      if _storage._deepMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._deepMs, fieldNumber: 10)
      }
      if _storage._remMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._remMs, fieldNumber: 11)
      }
      if _storage._awakeMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._awakeMs, fieldNumber: 12)
      }
      if _storage._eligibleSleepCount != 0 {
        try visitor.visitSingularInt32Field(value: _storage._eligibleSleepCount, fieldNumber: 13)
      }
      if !_storage._timezoneID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._timezoneID, fieldNumber: 14)
      }
      if _storage._napTotalSleepMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._napTotalSleepMs, fieldNumber: 15)
      }
      if _storage._napLightMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._napLightMs, fieldNumber: 16)
      }
      if _storage._napDeepMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._napDeepMs, fieldNumber: 17)
      }
      if _storage._napRemMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._napRemMs, fieldNumber: 18)
      }
      if _storage._napAwakeMs != 0 {
        try visitor.visitSingularInt64Field(value: _storage._napAwakeMs, fieldNumber: 19)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_SleepDaySummary, rhs: VitalOSProtocol_SleepDaySummary) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._dayStartTs != rhs_storage._dayStartTs {return false}
        if _storage._dayEndTs != rhs_storage._dayEndTs {return false}
        if _storage._updatedAtTs != rhs_storage._updatedAtTs {return false}
        if _storage._timezoneOffsetSeconds != rhs_storage._timezoneOffsetSeconds {return false}
        if _storage._mainSleepIndex != rhs_storage._mainSleepIndex {return false}
        if _storage._mainSleepStartTs != rhs_storage._mainSleepStartTs {return false}
        if _storage._mainSleepEndTs != rhs_storage._mainSleepEndTs {return false}
        if _storage._totalSleepMs != rhs_storage._totalSleepMs {return false}
        if _storage._lightMs != rhs_storage._lightMs {return false}
        if _storage._deepMs != rhs_storage._deepMs {return false}
        if _storage._remMs != rhs_storage._remMs {return false}
        if _storage._awakeMs != rhs_storage._awakeMs {return false}
        if _storage._eligibleSleepCount != rhs_storage._eligibleSleepCount {return false}
        if _storage._timezoneID != rhs_storage._timezoneID {return false}
        if _storage._napTotalSleepMs != rhs_storage._napTotalSleepMs {return false}
        if _storage._napLightMs != rhs_storage._napLightMs {return false}
        if _storage._napDeepMs != rhs_storage._napDeepMs {return false}
        if _storage._napRemMs != rhs_storage._napRemMs {return false}
        if _storage._napAwakeMs != rhs_storage._napAwakeMs {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_SleepDay: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SleepDay"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}summary\0\u{3}main_sleep_segments\0\u{1}naps\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._summary) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.mainSleepSegments) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.naps) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._summary {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.mainSleepSegments.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.mainSleepSegments, fieldNumber: 2)
    }
    if !self.naps.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.naps, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_SleepDay, rhs: VitalOSProtocol_SleepDay) -> Bool {
    if lhs._summary != rhs._summary {return false}
    if lhs.mainSleepSegments != rhs.mainSleepSegments {return false}
    if lhs.naps != rhs.naps {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_SleepDay.Nap: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = VitalOSProtocol_SleepDay.protoMessageName + ".Nap"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}segments\0\u{3}start_timestamp\0\u{3}end_timestamp\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.segments) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.startTimestamp) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.endTimestamp) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.segments.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.segments, fieldNumber: 1)
    }
    if self.startTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.startTimestamp, fieldNumber: 2)
    }
    if self.endTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.endTimestamp, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_SleepDay.Nap, rhs: VitalOSProtocol_SleepDay.Nap) -> Bool {
    if lhs.segments != rhs.segments {return false}
    if lhs.startTimestamp != rhs.startTimestamp {return false}
    if lhs.endTimestamp != rhs.endTimestamp {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_SleepDaySyncPayload: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SleepDaySyncPayload"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}day\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._day) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._day {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_SleepDaySyncPayload, rhs: VitalOSProtocol_SleepDaySyncPayload) -> Bool {
    if lhs._day != rhs._day {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_SleepSyncComplete: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SleepSyncComplete"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_SleepSyncComplete, rhs: VitalOSProtocol_SleepSyncComplete) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_SleepSyncNotification: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SleepSyncNotification"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}data\0\u{1}complete\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: VitalOSProtocol_SleepDaySyncPayload?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .data(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .data(v)
        }
      }()
      case 2: try {
        var v: VitalOSProtocol_SleepSyncComplete?
        var hadOneofValue = false
        if let current = self.payload {
          hadOneofValue = true
          if case .complete(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.payload = .complete(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.payload {
    case .data?: try {
      guard case .data(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .complete?: try {
      guard case .complete(let v)? = self.payload else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_SleepSyncNotification, rhs: VitalOSProtocol_SleepSyncNotification) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_RawStageChange: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RawStageChange"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}timestamp_ms\0\u{1}stage\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.timestampMs) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.stage) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.timestampMs != 0 {
      try visitor.visitSingularInt64Field(value: self.timestampMs, fieldNumber: 1)
    }
    if self.stage != .awake {
      try visitor.visitSingularEnumField(value: self.stage, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_RawStageChange, rhs: VitalOSProtocol_RawStageChange) -> Bool {
    if lhs.timestampMs != rhs.timestampMs {return false}
    if lhs.stage != rhs.stage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_CurrentSleepSessionState: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CurrentSleepSessionState"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}day_start_ms\0\u{3}session_start_ms\0\u{3}last_stage_change_ms\0\u{3}current_stage\0\u{3}accumulated_light_ms\0\u{3}accumulated_deep_ms\0\u{3}accumulated_rem_ms\0\u{3}accumulated_awake_ms\0\u{3}stage_changes\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.dayStartMs) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.sessionStartMs) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.lastStageChangeMs) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.currentStage) }()
      case 5: try { try decoder.decodeSingularInt64Field(value: &self.accumulatedLightMs) }()
      case 6: try { try decoder.decodeSingularInt64Field(value: &self.accumulatedDeepMs) }()
      case 7: try { try decoder.decodeSingularInt64Field(value: &self.accumulatedRemMs) }()
      case 8: try { try decoder.decodeSingularInt64Field(value: &self.accumulatedAwakeMs) }()
      case 9: try { try decoder.decodeRepeatedMessageField(value: &self.stageChanges) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.dayStartMs != 0 {
      try visitor.visitSingularInt64Field(value: self.dayStartMs, fieldNumber: 1)
    }
    if self.sessionStartMs != 0 {
      try visitor.visitSingularInt64Field(value: self.sessionStartMs, fieldNumber: 2)
    }
    if self.lastStageChangeMs != 0 {
      try visitor.visitSingularInt64Field(value: self.lastStageChangeMs, fieldNumber: 3)
    }
    if self.currentStage != .awake {
      try visitor.visitSingularEnumField(value: self.currentStage, fieldNumber: 4)
    }
    if self.accumulatedLightMs != 0 {
      try visitor.visitSingularInt64Field(value: self.accumulatedLightMs, fieldNumber: 5)
    }
    if self.accumulatedDeepMs != 0 {
      try visitor.visitSingularInt64Field(value: self.accumulatedDeepMs, fieldNumber: 6)
    }
    if self.accumulatedRemMs != 0 {
      try visitor.visitSingularInt64Field(value: self.accumulatedRemMs, fieldNumber: 7)
    }
    if self.accumulatedAwakeMs != 0 {
      try visitor.visitSingularInt64Field(value: self.accumulatedAwakeMs, fieldNumber: 8)
    }
    if !self.stageChanges.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.stageChanges, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_CurrentSleepSessionState, rhs: VitalOSProtocol_CurrentSleepSessionState) -> Bool {
    if lhs.dayStartMs != rhs.dayStartMs {return false}
    if lhs.sessionStartMs != rhs.sessionStartMs {return false}
    if lhs.lastStageChangeMs != rhs.lastStageChangeMs {return false}
    if lhs.currentStage != rhs.currentStage {return false}
    if lhs.accumulatedLightMs != rhs.accumulatedLightMs {return false}
    if lhs.accumulatedDeepMs != rhs.accumulatedDeepMs {return false}
    if lhs.accumulatedRemMs != rhs.accumulatedRemMs {return false}
    if lhs.accumulatedAwakeMs != rhs.accumulatedAwakeMs {return false}
    if lhs.stageChanges != rhs.stageChanges {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_SleepDataNotification: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SleepDataNotification"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}day_timestamp\0\u{3}is_main_sleep_complete\0\u{1}filename\0\u{3}total_sleep_minutes\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self.dayTimestamp) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isMainSleepComplete) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.filename) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.totalSleepMinutes) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.dayTimestamp != 0 {
      try visitor.visitSingularInt64Field(value: self.dayTimestamp, fieldNumber: 1)
    }
    if self.isMainSleepComplete != false {
      try visitor.visitSingularBoolField(value: self.isMainSleepComplete, fieldNumber: 2)
    }
    if !self.filename.isEmpty {
      try visitor.visitSingularStringField(value: self.filename, fieldNumber: 3)
    }
    if self.totalSleepMinutes != 0 {
      try visitor.visitSingularInt32Field(value: self.totalSleepMinutes, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_SleepDataNotification, rhs: VitalOSProtocol_SleepDataNotification) -> Bool {
    if lhs.dayTimestamp != rhs.dayTimestamp {return false}
    if lhs.isMainSleepComplete != rhs.isMainSleepComplete {return false}
    if lhs.filename != rhs.filename {return false}
    if lhs.totalSleepMinutes != rhs.totalSleepMinutes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
