// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: streaming.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// An enum for standardized reasons a stream might be canceled.
public enum VitalOSProtocol_CancelReason: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case reasonUnknown // = 0

  /// The user explicitly canceled the operation.
  case userCanceled // = 1

  /// The operation timed out.
  case timeout // = 2

  /// An unexpected error occurred.
  case streamInternalError // = 3

  /// The BLE connection was lost.
  case disconnected // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .reasonUnknown
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .reasonUnknown
    case 1: self = .userCanceled
    case 2: self = .timeout
    case 3: self = .streamInternalError
    case 4: self = .disconnected
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .reasonUnknown: return 0
    case .userCanceled: return 1
    case .timeout: return 2
    case .streamInternalError: return 3
    case .disconnected: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VitalOSProtocol_CancelReason] = [
    .reasonUnknown,
    .userCanceled,
    .timeout,
    .streamInternalError,
    .disconnected,
  ]

}

/// Initiates a stream.
public struct VitalOSProtocol_StartStream: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: Int32 = 0

  public var totalSize: Int64 = 0

  /// Additional context for the stream, parsed based on the specific Start Command used.
  public var context: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Context for API/REST streaming requests (Watch -> App)
public struct VitalOSProtocol_StreamApiRequestContext: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var requestID: String = String()

  /// GET, POST, PUT, DELETE, etc.
  public var method: String = String()

  public var url: String = String()

  public var headers: Dictionary<String,String> = [:]

  public var queryParams: Dictionary<String,String> = [:]

  /// The actual request body will be streamed via StreamDataChunk messages
  public var useAppAuth: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Context for streaming API response data back to watch (App -> Watch)
public struct VitalOSProtocol_StreamApiResponseContext: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Original request ID being responded to
  public var requestID: String = String()

  /// HTTP response status (200, 404, etc.)
  public var httpStatusCode: Int32 = 0

  /// Content-Type header value
  public var contentType: String = String()

  /// Other response headers (optional)
  public var headers: Dictionary<String,String> = [:]

  /// Suggested name for the file (optional)
  public var suggestedFileName: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A wrapper for a chunk of data for a stream.
public struct VitalOSProtocol_StreamDataChunk: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: Int32 = 0

  public var sequenceNumber: Int32 = 0

  public var data: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct VitalOSProtocol_StreamDataChunkAck: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: Int32 = 0

  public var sequenceNumber: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A message to signal the end of a stream and provide the final checksum.
public struct VitalOSProtocol_EndStream: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: Int32 = 0

  public var checksum: UInt32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// A command to cancel an in-progress data stream.
public struct VitalOSProtocol_CancelStream: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var streamID: Int32 = 0

  public var reasonCode: VitalOSProtocol_CancelReason = .reasonUnknown

  public var reasonMessage: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "VitalOSProtocol"

extension VitalOSProtocol_CancelReason: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0REASON_UNKNOWN\0\u{1}USER_CANCELED\0\u{1}TIMEOUT\0\u{1}STREAM_INTERNAL_ERROR\0\u{1}DISCONNECTED\0")
}

extension VitalOSProtocol_StartStream: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StartStream"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{3}total_size\0\u{1}context\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.totalSize) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.context) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularInt32Field(value: self.streamID, fieldNumber: 1)
    }
    if self.totalSize != 0 {
      try visitor.visitSingularInt64Field(value: self.totalSize, fieldNumber: 2)
    }
    if !self.context.isEmpty {
      try visitor.visitSingularBytesField(value: self.context, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_StartStream, rhs: VitalOSProtocol_StartStream) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.totalSize != rhs.totalSize {return false}
    if lhs.context != rhs.context {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_StreamApiRequestContext: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamApiRequestContext"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{1}method\0\u{1}url\0\u{1}headers\0\u{3}query_params\0\u{3}use_app_auth\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.method) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.url) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.headers) }()
      case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.queryParams) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.useAppAuth) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    if !self.method.isEmpty {
      try visitor.visitSingularStringField(value: self.method, fieldNumber: 2)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 3)
    }
    if !self.headers.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.headers, fieldNumber: 4)
    }
    if !self.queryParams.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.queryParams, fieldNumber: 5)
    }
    if self.useAppAuth != false {
      try visitor.visitSingularBoolField(value: self.useAppAuth, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_StreamApiRequestContext, rhs: VitalOSProtocol_StreamApiRequestContext) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.method != rhs.method {return false}
    if lhs.url != rhs.url {return false}
    if lhs.headers != rhs.headers {return false}
    if lhs.queryParams != rhs.queryParams {return false}
    if lhs.useAppAuth != rhs.useAppAuth {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_StreamApiResponseContext: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamApiResponseContext"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}request_id\0\u{3}http_status_code\0\u{3}content_type\0\u{1}headers\0\u{3}suggested_file_name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.requestID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.httpStatusCode) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.contentType) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.headers) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.suggestedFileName) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.requestID.isEmpty {
      try visitor.visitSingularStringField(value: self.requestID, fieldNumber: 1)
    }
    if self.httpStatusCode != 0 {
      try visitor.visitSingularInt32Field(value: self.httpStatusCode, fieldNumber: 2)
    }
    if !self.contentType.isEmpty {
      try visitor.visitSingularStringField(value: self.contentType, fieldNumber: 3)
    }
    if !self.headers.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.headers, fieldNumber: 4)
    }
    if !self.suggestedFileName.isEmpty {
      try visitor.visitSingularStringField(value: self.suggestedFileName, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_StreamApiResponseContext, rhs: VitalOSProtocol_StreamApiResponseContext) -> Bool {
    if lhs.requestID != rhs.requestID {return false}
    if lhs.httpStatusCode != rhs.httpStatusCode {return false}
    if lhs.contentType != rhs.contentType {return false}
    if lhs.headers != rhs.headers {return false}
    if lhs.suggestedFileName != rhs.suggestedFileName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_StreamDataChunk: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamDataChunk"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{3}sequence_number\0\u{1}data\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.sequenceNumber) }()
      case 3: try { try decoder.decodeSingularBytesField(value: &self.data) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularInt32Field(value: self.streamID, fieldNumber: 1)
    }
    if self.sequenceNumber != 0 {
      try visitor.visitSingularInt32Field(value: self.sequenceNumber, fieldNumber: 2)
    }
    if !self.data.isEmpty {
      try visitor.visitSingularBytesField(value: self.data, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_StreamDataChunk, rhs: VitalOSProtocol_StreamDataChunk) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.sequenceNumber != rhs.sequenceNumber {return false}
    if lhs.data != rhs.data {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_StreamDataChunkAck: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".StreamDataChunkAck"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{3}sequence_number\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.sequenceNumber) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularInt32Field(value: self.streamID, fieldNumber: 1)
    }
    if self.sequenceNumber != 0 {
      try visitor.visitSingularInt32Field(value: self.sequenceNumber, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_StreamDataChunkAck, rhs: VitalOSProtocol_StreamDataChunkAck) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.sequenceNumber != rhs.sequenceNumber {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_EndStream: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".EndStream"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{1}checksum\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.checksum) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularInt32Field(value: self.streamID, fieldNumber: 1)
    }
    if self.checksum != 0 {
      try visitor.visitSingularUInt32Field(value: self.checksum, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_EndStream, rhs: VitalOSProtocol_EndStream) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.checksum != rhs.checksum {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_CancelStream: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CancelStream"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}stream_id\0\u{3}reason_code\0\u{3}reason_message\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.streamID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.reasonCode) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.reasonMessage) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.streamID != 0 {
      try visitor.visitSingularInt32Field(value: self.streamID, fieldNumber: 1)
    }
    if self.reasonCode != .reasonUnknown {
      try visitor.visitSingularEnumField(value: self.reasonCode, fieldNumber: 2)
    }
    if !self.reasonMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.reasonMessage, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_CancelStream, rhs: VitalOSProtocol_CancelStream) -> Bool {
    if lhs.streamID != rhs.streamID {return false}
    if lhs.reasonCode != rhs.reasonCode {return false}
    if lhs.reasonMessage != rhs.reasonMessage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
