// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: vital_os.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// An enum for standardized error codes that can be sent in responses.
/// This allows the client app to handle errors programmatically.
/// Error Codes
///  OK = 0;                 // No error, the command was successful.
///  UNKNOWN_ERROR = 1;      // A generic, unknown error occurred.
///  INVALID_COMMAND = 2;    // The command received is not recognized.
///  INVALID_PARAMETER = 3;  // The parameters for the command were invalid.
///  INVALID_STATE = 4;      // The device was in the wrong state to execute the command.
///  NOT_SUPPORTED = 5;      // The feature is not supported on this device/firmware.
public enum VitalOSProtocol_VitalOSErrorCode: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int

  /// A generic, unknown error occurred.
  case unknownError // = 0

  /// The command received is not recognized.
  case invalidCommand // = 1

  /// The parameters for the command were invalid.
  case invalidParameter // = 2

  /// The device was in the wrong state to execute the command.
  case invalidState // = 3

  /// The feature is not supported on this device/firmware.
  case unsupported // = 4

  /// The device is too busy to process command
  case deviceBusy // = 5
  case UNRECOGNIZED(Int)

  public init() {
    self = .unknownError
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unknownError
    case 1: self = .invalidCommand
    case 2: self = .invalidParameter
    case 3: self = .invalidState
    case 4: self = .unsupported
    case 5: self = .deviceBusy
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unknownError: return 0
    case .invalidCommand: return 1
    case .invalidParameter: return 2
    case .invalidState: return 3
    case .unsupported: return 4
    case .deviceBusy: return 5
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [VitalOSProtocol_VitalOSErrorCode] = [
    .unknownError,
    .invalidCommand,
    .invalidParameter,
    .invalidState,
    .unsupported,
    .deviceBusy,
  ]

}

/// A single, standardized wrapper for ALL solicited responses to commands.
/// This is defined here because it aggregates types from multiple imported files.
public struct VitalOSProtocol_CommandResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Indicates if the command was successfully processed.
  public var success: Bool = false

  /// Optional: Provides a human-readable error message if success is false.
  public var errorMessage: String = String()

  /// Optional: Error code
  public var errorCode: VitalOSProtocol_VitalOSErrorCode = .unknownError

  /// Optional: Provides a human-readable status message when success is true.
  public var statusMessage: String = String()

  /// Optional: Payload of response if command expects data in return
  public var payload: Data = Data()

  /// Optional: For sync commands, number of records/items to expect (0 = no data).
  /// Sleep sync: number of SleepDay items; health sync: 0 = no data, 1 = data will be streamed.
  public var recordCount: Int32 {
    get {_recordCount ?? 0}
    set {_recordCount = newValue}
  }
  /// Returns true if `recordCount` has been explicitly set.
  public var hasRecordCount: Bool {self._recordCount != nil}
  /// Clears the value of `recordCount`. Subsequent reads from it will return its default value.
  public mutating func clearRecordCount() {self._recordCount = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _recordCount: Int32? = nil
}

/// Empty payload for commands that require no parameters (e.g. enable/disable data sync).
public struct VitalOSProtocol_Empty: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// App -> Watch: Set the device environment (prod, qa, dev).
public struct VitalOSProtocol_SetEnvironment: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// "prod", "qa", or "dev"
  public var env: String = String()

  /// optional override; empty means not set
  public var customURL: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// App -> Watch: request current device info.
public struct VitalOSProtocol_GetDeviceInfoRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// Watch -> App: full device information snapshot.
public struct VitalOSProtocol_DeviceInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var firmwareVersion: String = String()

  public var colorID: Int32 = 0

  public var sku: String = String()

  public var serialNumber: String = String()

  public var macAddress: String = String()

  public var productCode: String = String()

  public var productYear: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// App -> Watch: request current user profile.
public struct VitalOSProtocol_GetUserProfileRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// App <-> Watch: user profile payload.
public struct VitalOSProtocol_UserProfile: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var age: Int32 = 0

  public var sex: Int32 = 0

  public var height: Int32 = 0

  public var weight: Int32 = 0

  public var wearingHand: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "VitalOSProtocol"

extension VitalOSProtocol_VitalOSErrorCode: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0UNKNOWN_ERROR\0\u{1}INVALID_COMMAND\0\u{1}INVALID_PARAMETER\0\u{1}INVALID_STATE\0\u{1}UNSUPPORTED\0\u{1}DEVICE_BUSY\0")
}

extension VitalOSProtocol_CommandResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CommandResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{3}error_message\0\u{3}error_code\0\u{1}payload\0\u{3}record_count\0\u{3}status_message\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.errorMessage) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.errorCode) }()
      case 4: try { try decoder.decodeSingularBytesField(value: &self.payload) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self._recordCount) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.statusMessage) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.errorMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.errorMessage, fieldNumber: 2)
    }
    if self.errorCode != .unknownError {
      try visitor.visitSingularEnumField(value: self.errorCode, fieldNumber: 3)
    }
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 4)
    }
    try { if let v = self._recordCount {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
    } }()
    if !self.statusMessage.isEmpty {
      try visitor.visitSingularStringField(value: self.statusMessage, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_CommandResponse, rhs: VitalOSProtocol_CommandResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.errorMessage != rhs.errorMessage {return false}
    if lhs.errorCode != rhs.errorCode {return false}
    if lhs.statusMessage != rhs.statusMessage {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs._recordCount != rhs._recordCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_Empty: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Empty"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_Empty, rhs: VitalOSProtocol_Empty) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_SetEnvironment: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SetEnvironment"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}env\0\u{3}custom_url\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.env) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.customURL) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.env.isEmpty {
      try visitor.visitSingularStringField(value: self.env, fieldNumber: 1)
    }
    if !self.customURL.isEmpty {
      try visitor.visitSingularStringField(value: self.customURL, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_SetEnvironment, rhs: VitalOSProtocol_SetEnvironment) -> Bool {
    if lhs.env != rhs.env {return false}
    if lhs.customURL != rhs.customURL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_GetDeviceInfoRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetDeviceInfoRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_GetDeviceInfoRequest, rhs: VitalOSProtocol_GetDeviceInfoRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_DeviceInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}firmware_version\0\u{3}color_id\0\u{1}sku\0\u{3}serial_number\0\u{3}mac_address\0\u{3}product_code\0\u{3}product_year\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.firmwareVersion) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.colorID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.sku) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.serialNumber) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.macAddress) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.productCode) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self.productYear) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.firmwareVersion.isEmpty {
      try visitor.visitSingularStringField(value: self.firmwareVersion, fieldNumber: 1)
    }
    if self.colorID != 0 {
      try visitor.visitSingularInt32Field(value: self.colorID, fieldNumber: 2)
    }
    if !self.sku.isEmpty {
      try visitor.visitSingularStringField(value: self.sku, fieldNumber: 3)
    }
    if !self.serialNumber.isEmpty {
      try visitor.visitSingularStringField(value: self.serialNumber, fieldNumber: 4)
    }
    if !self.macAddress.isEmpty {
      try visitor.visitSingularStringField(value: self.macAddress, fieldNumber: 5)
    }
    if !self.productCode.isEmpty {
      try visitor.visitSingularStringField(value: self.productCode, fieldNumber: 6)
    }
    if self.productYear != 0 {
      try visitor.visitSingularInt32Field(value: self.productYear, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_DeviceInfo, rhs: VitalOSProtocol_DeviceInfo) -> Bool {
    if lhs.firmwareVersion != rhs.firmwareVersion {return false}
    if lhs.colorID != rhs.colorID {return false}
    if lhs.sku != rhs.sku {return false}
    if lhs.serialNumber != rhs.serialNumber {return false}
    if lhs.macAddress != rhs.macAddress {return false}
    if lhs.productCode != rhs.productCode {return false}
    if lhs.productYear != rhs.productYear {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_GetUserProfileRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".GetUserProfileRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_GetUserProfileRequest, rhs: VitalOSProtocol_GetUserProfileRequest) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension VitalOSProtocol_UserProfile: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UserProfile"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}age\0\u{1}sex\0\u{1}height\0\u{1}weight\0\u{3}wearing_hand\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.age) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.sex) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.height) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self.weight) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.wearingHand) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.age != 0 {
      try visitor.visitSingularInt32Field(value: self.age, fieldNumber: 1)
    }
    if self.sex != 0 {
      try visitor.visitSingularInt32Field(value: self.sex, fieldNumber: 2)
    }
    if self.height != 0 {
      try visitor.visitSingularInt32Field(value: self.height, fieldNumber: 3)
    }
    if self.weight != 0 {
      try visitor.visitSingularInt32Field(value: self.weight, fieldNumber: 4)
    }
    if self.wearingHand != 0 {
      try visitor.visitSingularInt32Field(value: self.wearingHand, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: VitalOSProtocol_UserProfile, rhs: VitalOSProtocol_UserProfile) -> Bool {
    if lhs.age != rhs.age {return false}
    if lhs.sex != rhs.sex {return false}
    if lhs.height != rhs.height {return false}
    if lhs.weight != rhs.weight {return false}
    if lhs.wearingHand != rhs.wearingHand {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
